### PR TITLE
Solve admin authorization

### LINKED ISSUE #36: Admin authorization
Now that we are beginning to reach a point, where everything seems to be working in tact, we should implement helper methods in the `ApplicationHelper` to help us determine, if the user logged into the session (`@user`) is an admin, so that this handy helper function could be used on the frontend when showing a button or not.
Also, we need to have some `before_action` methods in the controllers, so that no unauthorized action could be carried out on the backend.

### PR DESCRIPTION
**Pull request by triszt4n**
Closes #36 

### What's new:
* Check certain queries that need admin authority on backend :steam_locomotive: 
* Restrict certain frontend components to admin authority :lock: 
* Remove unused helpers :broom:

### CODE REVIEW

**Review by SepsiLaszlo — CHANGES_REQUESTED** [review]
Good work!

I noticed that yout deleted the helper files. Why was that necessary?

**Comment by triszt4n** [comment]
Oh no, I made that commit thousands of years ago and forgot to get rid of that, gonna put back (saw some good usecases of them, maybe we'll use 'em)

**Review by SepsiLaszlo — APPROVED** [review]
👍

**Review by bbucsy — APPROVED** [review]
:partying_face:

**Pull request merged**
